
spring:
    datasource:
        url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
        username: sa
        password:
        driver-class-name: org.h2.Driver
        initialization-mode: ALWAYS 
    jpa:
      hibernate:
        ddl-auto: update
      generate-ddl: true

    h2:
        console:
            enabled: true